---
# Record what Ansible thinks the correct SSH port is for later use.
- ansible.builtin.set_fact:
    custom_port: "{{ ansible_port }}"

# Have Ansible check if {{ inventory_hostname }} is currently listening on port 22
- name: SSH Port > Detect > Check Default(22) > {{ inventory_hostname}}
  ansible.builtin.wait_for:
    port: "22"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "10"
  delegate_to: "localhost"
  ignore_errors: true
  register: default_ssh

# If reachable, ensure ansible_port is set to (22)
- ansible.builtin.set_fact:
    ansible_port: "22"
  when: 
    - default_ssh is defined
    - not default_ssh.failed
    - default_ssh.state == "started"
  register: ssh_port_set

# Fail if unreachable and the configured port is also (22)
- name: SSH Port > Detect > Not Custom > Unreachable > FAIL
  ansible.builtin.fail:
    msg: "Remote host is not available on port 22 or custom port not set."
  when: 
    - default_ssh is defined
    - default_ssh.failed
    - default_ssh.state is undefined
    - ansible_port == 22

# If unreachable on port 22, check if {{ inventory_hostname }} 
# is reachable on {{ ansible_port }} provided by the inventory
- name: SSH Port > Detect > Custom > Check ({{ ansible_port }})
  ansible.builtin.wait_for:
    port: "{{ ansible_port }}"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "10"
  delegate_to: "localhost"
  ignore_errors: true
  register: configured_ssh
  when: 
    - default_ssh is defined
    - default_ssh.failed
    - default_ssh.state is undefined

# If {{ ansible_port }} is reachable, then carry on
- name: SSH Port > Detect > Verify Reachable > Port ({{ ansible_port }})
  ansible.builtin.debug:
    msg: "SSH port is configured properly"
  when: 
    - configured_ssh is defined
    - configured_ssh.skipped is not defined
    - configured_ssh.state == "started"
  register: ssh_port_set

# Fail if the SSH port is neither the default or the custom port.
- name: SSH Port > Detect > Unreachable > FAIL Unknown Port ({{ ansible_port }})
  ansible.builtin.fail:
    msg: "The SSH port is neither 22 or {{ ansible_port }}."
  when: ssh_port_set is undefined
