---
# Add IP address via DNS lookup if just a hostname.
- name: SSH > Fingerprint > Discover Connection Endpoints
  ansible.builtin.set_fact:
    ssh_hosts: >-
      {{ inventory_hostname }}
      {% if inventory_hostname | ansible.utils.ipaddr is sameas false %},
      {{ lookup('pipe', 'dig +short ' + inventory_hostname) | replace('\n', ',')}}
      {% endif %}"
    ssh_port: "{{ ansible_port | default(22) }}"

- name: SSH > Fingerprint > Massage ssh_host output
  ansible.builtin.set_fact:
    ssh_hosts: "{{ ssh_host | replace(' ', '') }}"

- name: SSH > Fingerprint > Debug > Connection Endpoints
  ansible.builtin.debug:
    var: ssh_hosts

- name: SSH > Fingerprint > Record SSH Keys (RSA, DSA, ECDSA, ED25519)
  ansible.builtin.set_fact:
    host_keys:
      rsa: "{{ lookup('pipe', 'ssh-keyscan -trsa -p' + ssh_port + ' ' + ssh_hosts, errors='ignore') }}"
      dsa: "{{ lookup('pipe', 'ssh-keyscan -tdsa -p' + ssh_port + ' ' + ssh_hosts, errors='ignore') }}"
      ecdsa: "{{ lookup('pipe', 'ssh-keyscan -tecdsa -p' + ssh_port + ' ' + ssh_hosts, errors='ignore') }}"
      ecdsask: "{{ lookup('pipe', 'ssh-keyscan -tecdsa-sk -p' + ssh_port + ' ' + ssh_hosts, errors='ignore') }}"
      ed25519: "{{ lookup('pipe', 'ssh-keyscan -ted25519 -p' + ssh_port + ' ' + ssh_hosts, errors='ignore') }}"
      ed25519sk: "{{ lookup('pipe', 'ssh-keyscan -ted25519-sk -p' + ssh_port + ' ' + ssh_hosts, errors='ignore') }}"

# - name: SSH > Fingerprint > Debug > Host Keys
#   ansible.builtin.debug:
#     var: host_keys

- name: SSH > Fingerprint > Assert > Minimum 1 key found
  ansible.builtin.fail:
    msg: No SSH Host Key found!
  when:
    - host_keys.rsa == ''
    - host_keys.dsa == ''
    - host_keys.ecdsa == ''
    - host_keys.ecdsask == ''
    - host_keys.ed25519 == ''
    - host_keys.ed25519sk == ''

- ansible.builtin.set_fact:
    known_hosts_filepath: "{% if global_known_hosts %}/etc/ssh/{% else %}~/.ssh/{% endif %}known_hosts.d/"
    known_hosts_systempath: "/etc/ssh/known_hosts.d/"
    known_hosts_userpath: "~/.ssh/known_hosts.d/"

- name: SSH > Fingerprint > Create Known Hosts Folder > {{ known_hosts_systempath }}
  ansible.builtin.file:
    path: "{{ known_hosts_systempath }}"
    state: directory
    mode: '0755'
  become: true
  delegate_to: "localhost"

- name: SSH > Fingerprint > Create Known Hosts Folder > {{ known_hosts_userpath }}
  ansible.builtin.file:
    path: "{{ known_hosts_userpath }}"
    state: directory
    mode: '0700'
  become: false
  delegate_to: "localhost"

- name: SSH > Fingerprint > Configure SSH Option > HashKnownHosts
  ansible.builtin.lineinfile:
    path: /etc/ssh/ssh_config
    regexp: '^    HashKnownHosts'
    line: "    HashKnownHosts no"
  become: true
  delegate_to: "localhost"

- name: SSH > Fingerprint > Configure SSH Option > GlobalKnownHostsFile
  ansible.builtin.lineinfile:
    path: /etc/ssh/ssh_config
    regexp: '^    GlobalKnownHostsFile'
    line: "    GlobalKnownHostsFile {{ known_hosts_systempath }}%n /etc/ssh/known_hosts"
  become: true
  delegate_to: "localhost"

- name: SSH > Fingerprint > Configure SSH Option > UserKnownHostsFile
  ansible.builtin.lineinfile:
    path: /etc/ssh/ssh_config
    regexp: '^    UserKnownHostsFile'
    line: "    UserKnownHostsFile {{ known_hosts_userpath }}%n ~/.ssh/known_hosts"
  become: true
  delegate_to: "localhost"

- name: SSH > Fingerprint > Host Key > Diff > {{ known_hosts_filepath }}
  ansible.builtin.blockinfile:
    backup: true
    marker: "# {mark} SSH Keys for {{ inventory_hostname }}"
    create: true
    path: "{{ known_hosts_filepath }}{{ inventory_hostname }}"
    mode: 0644
    block: |
      {{ host_keys.rsa | default('# RESERVED FOR RSA KEY', true) }}
      {{ host_keys.dsa | default('# RESERVED FOR DSA KEY', true) }}
      {{ host_keys.ecdsa | default('# RESERVED FOR ECDSA KEY', true) }}
      {{ host_keys.ecdsask | default('# RESERVED FOR ECDSA-SK KEY', true) }}
      {{ host_keys.ed25519 | default('# RESERVED FOR ED25519 KEY', true) }}
      {{ host_keys.ed25519sk | default('# RESERVED FOR ED25519-SK KEY', true) }}
  check_mode: true
  diff: true
  become: false
  delegate_to: "localhost"
  register: check_host_entry
  when: verify_host_keys | default(true)

# - name: SSH > Fingerprint > Debug > Host Keys
#   debug:
#     var: check_host_entry
#   when:
#     - check_host_entry.changed

- name: SSH > Fingerprint > Alert > SSH Host Key changed!
  ansible.builtin.pause:
    prompt: The Host's SSH key has changed, press return to continue. Press Ctrl+c and then "a" to abort
  when:
    - check_host_entry.changed
    - verify_host_keys | default(true)

- name: SSH > Fingerprint > Host Keys > Commit Changes > {{ known_hosts_filepath }}
  ansible.builtin.blockinfile:
    backup: true
    marker: "# {mark} SSH Keys for {{ inventory_hostname }}"
    create: true
    path: "{{ known_hosts_filepath }}{{ inventory_hostname }}"
    # mode: "{{ '644' if global_known_hosts == true else '600' }}"
    mode: 0644
    block: |
      {{ host_keys.rsa | default('# RESERVED FOR RSA KEY', true) }}
      {{ host_keys.dsa | default('# RESERVED FOR DSA KEY', true) }}
      {{ host_keys.ecdsa | default('# RESERVED FOR ECDSA KEY', true) }}
      {{ host_keys.ecdsask | default('# RESERVED FOR ECDSA-SK KEY', true) }}
      {{ host_keys.ed25519 | default('# RESERVED FOR ED25519 KEY', true) }}
      {{ host_keys.ed25519sk | default('# RESERVED FOR ED25519-SK KEY', true) }}
  become: "{{ global_known_hosts }}"
  delegate_to: "localhost"
